-- 즐겨찾기가 가장 많은 식당 정보 출력하기
-- 프로그래머스 중급 (⭐⭐⭐)
-- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/131123
-- 작성자: 김효준
-- 작성일: 2026. 06. 16. 16:42:02

-- 코드를 입력하세요
# SELECT
#     FOOD_TYPE,
#     REST_ID,
#     REST_NAME,
#     FAVORITES
# FROM (
# SELECT 
#         FOOD_TYPE,
#     REST_ID,
#     REST_NAME,
#     FAVORITES,
#     RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RN
#     FROM REST_INFO
# ) B
# WHERE RN = 1
# ORDER BY FOOD_TYPE DESC

# SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
# FROM REST_INFO A
# INNER JOIN (
#     SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
#     FROM REST_INFO
#     GROUP BY FOOD_TYPE
# ) B ON A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = B.MAX_FAVORITES
# ORDER BY FOOD_TYPE DESC;

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;