-- 취소되지 않은 진료 예약 조회하기
-- 프로그래머스 중급 (⭐⭐⭐)
-- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/132204
-- 작성자: 김효준
-- 작성일: 2026. 06. 16. 16:45:34

-- 코드를 입력하세요
SELECT AP.APNT_NO, P.PT_NAME, AP.PT_NO, AP.MCDP_CD, D.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AP
JOIN DOCTOR D
ON D.DR_ID = AP.MDDR_ID
JOIN PATIENT P ON P.PT_NO = AP.PT_NO
WHERE DATE_FORMAT(DATE(APNT_YMD), '%Y-%m-%d') = '2022-04-13'
AND AP.APNT_CNCL_YMD IS NULL
AND AP.MCDP_CD = 'CS'
ORDER BY AP.APNT_YMD

# SELECT AP.APNT_NO, P.PT_NAME, AP.PT_NO, AP.MCDP_CD, D.DR_NAME, AP.APNT_YMD
# FROM APPOINTMENT AP 
# JOIN DOCTOR D ON D.DR_ID = AP.MDDR_ID
# JOIN PATIENT P ON P.PT_NO = AP.PT_NO
# WHERE AP.APNT_CNCL_YMD IS NULL AND AP.MCDP_CD = 'CS' AND AP.APNT_YMD LIKE '2022-04-13%'
# ORDER BY AP.APNT_YMD