-- 입양 시각 구하기(2)
-- 프로그래머스 고급 (⭐⭐⭐⭐)
-- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/59413
-- 작성자: 김효준
-- 작성일: 2026. 06. 17. 14:57:07

-- 코드를 입력하세요

# WITH RECURSIVE HOURS AS (
#     SELECT 0 AS HOUR
#     UNION ALL
#     SELECT HOUR + 1
#     FROM HOURS
#     WHERE HOUR < 23
# )
# SELECT
#     H.HOUR,
#     COUNT(A.ANIMAL_ID) AS COUNT
# FROM HOURS H
# LEFT JOIN ANIMAL_OUTS A
#     ON H.HOUR = HOUR(A.DATETIME)
# GROUP BY H.HOUR
# ORDER BY H.HOUR;

SELECT 
    H.HOUR,
    COUNT(A.ANIMAL_ID) AS COUNT
FROM (
    SELECT 0 AS HOUR UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3
    UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7
    UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11
    UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
    UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
    UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23
) H
LEFT JOIN ANIMAL_OUTS A
    ON H.HOUR = HOUR(A.DATETIME)
GROUP BY H.HOUR
ORDER BY H.HOUR;