-- 상품을 구매한 회원 비율 구하기
-- 프로그래머스 고급 (⭐⭐⭐⭐)
-- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/131534
-- 작성자: 김효준
-- 작성일: 2026. 06. 17. 14:57:17

# # -- 코드를 입력하세요
SELECT 
    YEAR(B.SALES_DATE) AS YEAR, 
    MONTH(B.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERES,
    ROUND(COUNT(DISTINCT A.USER_ID) * 1.0 / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1)
    AS PURCHASED_RATIO
FROM USER_INFO A
JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
WHERE YEAR(A.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH